language: android
android:
   components:

   # The BuildTools version used by project
   - platform-tools
   - tools
   - build-tools-26.0.2
   # The SDK version used to complie project
   - android-19
   #Additional components

addons:
   sonarcloud:
      organization: "madewithpaper-github"
      token:
         secure: "0e2812484539455a0287fd3b0759a4f7f867875f"

   script:
      - echo "Travis branch is $TRAVIS_BRANCH"
      - echo "Travis branc is in pull request $TRAVIS_PULL+REQUEST"
      - sonar-scanner
