language: android
sudo: true

cache:
   directories:
      - ${TRAVIS_BUILD_DIR}/gradle/caches/
      - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

android:
   components:

   # The BuildTools version used by project
   - tools
   - platform-tools
   - tools
   - build-tools-26.0.2
   # The SDK version used to complie project
   - android-26
   - extra-google-m2repository
   - extra-android-m2repository
   #Additional components
jdk:
  - oraclejdk8

licenses:
   - 'android-sdk-preview-license-.+'
   - 'android-sdk-license-.+'
   - 'google-gdk-license-.+'

script:
   - chmod +x ./Simternship/gradlew
   - cd Simternship
   - echo "Build project"
   - ./Simternship/gradlew build
   - echo "Run sonarqube -- push to sonarcloud"
   - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=madewithpaper-github -Dsonar.login="$SONAR_TOKEN" -Dsonar.branch.name=master
notifications:
   email:
      recipients:
         - huangjacky.1996@gmail.com
         - anniemo1002@gmail.com
         - dziermanfelix@gmail.com
         - mdbrown7079@gmail.com
         - joeldentici@gmail.com

   on_success: change
   on_failure: change
