language: android
sudo: true

cache:
   directories:
      - ${TRAVIS_BUILD_DIR}/gradle/caches/
      - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

android:
   components:

   # The BuildTools version used by project
   - tools
   - platform-tools
   - tools
   - build-tools-26.0.2
   # The SDK version used to complie project
   - android-26
   - extra-google-m2repository
   - extra-android-m2repository
   #Additional components
jdk:
  - oraclejdk8

licenses:
   - 'android-sdk-preview-license-.+'
   - 'android-sdk-license-.+'
   - 'google-gdk-license-.+'

addons:
   sonarcloud:
      organization: "madewithpaper-github"
      token:
         secure: "5b66b857b862c05a65c6fd6f5a4503ef5064fd9a"

script:
   - echo "Travis branch is $TRAVIS_BRANCH"
   - echo "Travis branc is in pull request $TRAVIS_PULL+REQUEST"
   - ./gradlew sonarqube

notifications:
   email:
      recipients:
         - huangjacky.1996@gmail.com
         - anniemo1002@gmail.com
         - dziermanfelix@gmail.com
         - mdbrown7079@gmail.com
         - joeldentici@gmail.com

   on_success: change
   on_failure: change
