lnguage: android
android:
   components:

   # The BuildTools version used by project
   - platform-tools
   - tools
   - build-tools-26.0.2
   # The SDK version used to complie project
   - android-19
   #Additional components
dist: trusty
addons:
   sonarcloud:
      organization: "madewithpaper-github"
      token:
         secure: "462817f6fa5c37f721a34dfd936f2ec6d13398f2"

   script:
      - echo "Travis branch is $TRAVIS_BRANCH"
      - echo "Travis branc is in pull request $TRAVIS_PULL+REQUEST"
      - ./gradlew sonarqube

cache:
  directories:
      - '$HOME/.m2/repository'
          - '$HOME/.sonar/cache'
              - '$HOME/.gradle'
                  - '.gradle'
notifications:
   email:
      recipients:
         - huangjacky.1996@gmail.com
         - anniemo1002@gmail.com
         - dziermanfelix@gmail.com
         - mdbrown7079@gmail.com
         - joeldentici@gmail.com

   on_success: change
   on_failure: change
