language: android
sudo: true

cache:
   directories:
      - ${TRAVIS_BUILD_DIR}/gradle/caches/
      - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

android:
   components:

   # The BuildTools version used by project
   - tools
   - platform-tools
   - tools
   - build-tools-26.0.2
   # The SDK version used to complie project
   - android-26
   - extra-google-m2repository
   - extra-android-m2repository
   #Additional components
jdk:
  - oraclejdk8

licenses:
   - 'android-sdk-preview-license-.+'
   - 'android-sdk-license-.+'
   - 'google-gdk-license-.+'

addons:
   sonarcloud:
      organization: "madewithpaper-github"
      token:
         secure: "Sonar_Simternship"

script:
   - chmod +x ./Simternship/gradlew
   - echo "Travis branch is $TRAVIS_BRANCH"
   - echo "Travis branc is in pull request $TRAVIS_PULL+REQUEST"
   - ./Simternship/gradlew build
   - ./Simternship/gradlew sonarqube  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.organization=madewithpaper-github  -Dsonar.login=5dc62d3156c97cce7a1f9dc95d346f95cabd8798  -Dsonar.branch.name=master
notifications:
   email:
      recipients:
         - huangjacky.1996@gmail.com
         - anniemo1002@gmail.com
         - dziermanfelix@gmail.com
         - mdbrown7079@gmail.com
         - joeldentici@gmail.com

   on_success: change
   on_failure: change
